# Generated by Django 4.0.4 on 2022-04-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='cataloguebib',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='fonddocumentaire',
        ),
        migrations.AddField(
            model_name='documentation',
            name='documentation_type',
            field=models.CharField(choices=[('fondsdocumentaire', 'Fonds Documentaire'), ('cataloguebib', 'Catalogue Bibliothéque')], default='', max_length=25),
            preserve_default=False,
        ),
    ]
